# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC006():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC006(self):
    self.driver.get("http://127.0.0.1:5500/login.html")
    self.driver.set_window_size(807, 875)
    self.driver.find_element(By.ID, "btn-entrar").click()
    self.driver.find_element(By.ID, "btn-adicionar").click()
    self.driver.find_element(By.ID, "btn-adicionar").click()
    self.driver.find_element(By.ID, "nome").click()
    self.driver.find_element(By.ID, "nome").send_keys("Produto X")
    self.driver.find_element(By.ID, "quantidade").click()
    self.driver.find_element(By.ID, "quantidade").send_keys("5")
    self.driver.find_element(By.ID, "valor").click()
    self.driver.find_element(By.ID, "valor").send_keys("100")
    self.driver.find_element(By.ID, "data").click()
    self.driver.find_element(By.ID, "data").send_keys("2025-07-01")
    self.driver.find_element(By.ID, "btn-salvar").click()
    self.driver.find_element(By.ID, "btn-sair").click()
    self.driver.find_element(By.ID, "btn-sair").click()
  
