# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTC007():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_tC007(self):
    self.driver.get("http://127.0.0.1:5500/login.html")
    self.driver.set_window_size(829, 875)
    self.driver.find_element(By.ID, "btn-entrar").click()
    self.driver.find_element(By.ID, "btn-adicionar").click()
    self.driver.find_element(By.ID, "btn-adicionar").click()
    self.driver.find_element(By.ID, "codigo").click()
    self.driver.find_element(By.ID, "codigo").send_keys("X")
    self.driver.find_element(By.ID, "nome").click()
    self.driver.find_element(By.ID, "nome").send_keys("Produto @#!")
    self.driver.find_element(By.ID, "quantidade").click()
    self.driver.find_element(By.ID, "quantidade").send_keys("5")
    self.driver.find_element(By.ID, "valor").click()
    self.driver.find_element(By.ID, "valor").send_keys("100")
    self.driver.find_element(By.ID, "data").click()
    self.driver.find_element(By.ID, "data").send_keys("2025-07-01")
    self.driver.find_element(By.ID, "btn-salvar").click()
    element = self.driver.find_element(By.ID, "btn-salvar")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "btn-sair").click()
  
